// try catch

const numero1 = 90;
const numero3 = 80;

console.log(numero1);
try {
    console.log(numero2);    
} catch (error) {
    console.log(error);
}
console.log(numero3);